version: '3'

services:
  express:
    container_name: express
    image: hasanify/goodslogger:latest
    # labels:
    #   - com.centurylinklabs.watchtower.enable=true
    restart: always
    ports:
      - '3000:3000'
    links:
      - postgres
    depends_on:
      - postgres
      # - watchtower
    volumes:
      - ./dist:/express/srcc
      - ./pm2_logs:/root/.pm2/logs
    environment:
      PM2_PUBLIC_KEY: ${PM2_PUBLIC_KEY}
      PM2_SECRET_KEY: ${PM2_SECRET_KEY}
      PORT: ${PORT}
    command: 'npx nodemon -L'

  postgres:
    container_name: postgres
    image: postgres:16
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer:4
    restart: always
    ports:
      - 8080:8080
    links:
      - postgres

  # watchtower:
  #   container_name: watchtower
  #   image: containrrr/watchtower
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   restart: always
  #   command: --interval 30
