name: Docker Image CI

on:
  push:
    branches: ["main"]
    paths:
      - "api/**"
  pull_request:
    branches: ["main"]
    paths:
      - "api/**"

jobs:
  build:
    name: Build and Publish Image
    runs-on: ubuntu-latest
    concurrency: deploy-group

    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: docker build . --file api/Dockerfile --tag docker push hasanify/thingzcloud:latest
      - run: docker push hasanify/thingzcloud:latest
